#!/bin/bash

set -e

git rev-list --reverse HEAD |
while read rev; do
  read -p "Progress through history?" yn </dev/tty
    case $yn in
      [Yy]* ) git show $rev | view -; break;;
      [Nn]* ) exit;;
      * ) echo "Please answer yes or no.";;
    esac
done
